def raise_exception():
   raise TypeError('Exception has been raised')
